In [ ]:
!pip install keras-bert


  Created wheel for keras-bert: filename=keras_bert-0.88.0-py3-none-any.whl size=34204 sha256=3080bdc204a246ce81e634657d27fb927f763ec9de6c64cf748d77c8eafa4a5e
  Stored in directory: /root/.cache/pip/wheels/a2/90/cd/c038f2366929a3a5e3414a303b673e10235e802d871d29a835
  Created wheel for keras-transformer: filename=keras_transformer-0.39.0-py3-none-any.whl size=12842 sha256=328b317b0821a59415f3268433869438dfcb61b11efbdb6bdac3cb9827c136bf
  Stored in directory: /root/.cache/pip/wheels/bc/01/e0/5a1a14bed6726f2ed73f7917d2d2c2d4081d2c88426dea07ce
  Created wheel for keras-embed-sim: filename=keras_embed_sim-0.9.0-py3-none-any.whl size=4504 sha256=e0ea4142e6f0c0f94a7e923381ae4b8ac7d8c15a6da2596e93d893559e0fcbbe
  Stored in directory: /root/.cache/pip/wheels/a8/1e/d2/9bc15513dd2f8b9de3e628b3aa9d2de49e721deef6bbd1497e
  Created wheel for keras-layer-normalization: filename=keras_layer_normalization-0.15.0-py3-none-any.whl size=5224 sha256=5db2378093348d1a70ec9bcd4af66adee19a6b75ae07075f6178fd960

In [ ]:
import requests
from keras_bert import extract_embeddings, load_vocabulary, Tokenizer
import csv
import numpy as np
from collections import Counter

In [ ]:
# model_path = 'content'
model_path = '/content/drive/MyDrive/TM PA3/uncased_L-12_H-768_A-12'
dict_path = '/content/drive/MyDrive/TM PA3/uncased_L-12_H-768_A-12/vocab.txt'

In [ ]:
# Get Data from Ceiba
url = 'https://ceiba.ntu.edu.tw/course/88ca22/content/training.txt'
content = requests.get(url).content
content = content.decode('utf-8')

data = {}
content = content.replace(' \r', '').replace(' ', ',').strip().split('\n')

for c in content:
    if c.startswith('13'):
        c = c[:-1]  # direct downloading has a weird " " at the end
    c = [int(x) for x in c.split(',')]
    data[ c[0] ] = c[1:]

# PA3

In [ ]:
text_input = []

for i in range(1, 1096):
  with open(f'/content/drive/MyDrive/TM PA3/PA-1/{i}.txt', mode='r', encoding='utf-8') as f:
    whole_paragraph = ''
    for line in f:
      whole_paragraph += ( line.lower().strip()+' ' )
    text_input.append( whole_paragraph.strip() )

In [ ]:
text_input

In [ ]:
embeddings = extract_embeddings( model_path , text_input[:5] )

In [ ]:
embeddings = extract_embeddings( model_path , text_input )

In [ ]:
print(len(embeddings))
print(len(embeddings[0]))
print(len(embeddings[1]))
print(len(embeddings[0][0]))
print(len(embeddings[1][0]))

print(embeddings[1])

In [ ]:
cls_vecs = np.array( [x[0] for x in embeddings] )

In [ ]:
cls_vecs.shape

(1095, 768)

In [ ]:
for cls, vals in data.items():
  print(cls, vals)

1 [11, 19, 29, 113, 115, 169, 278, 301, 316, 317, 321, 324, 325, 338, 341]
2 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16]
3 [813, 817, 818, 819, 820, 821, 822, 824, 825, 826, 828, 829, 830, 832, 833]
4 [635, 680, 683, 702, 704, 705, 706, 708, 709, 719, 720, 722, 723, 724, 726]
5 [646, 751, 781, 794, 798, 799, 801, 812, 815, 823, 831, 839, 840, 841, 842]
6 [995, 998, 999, 1003, 1005, 1006, 1007, 1009, 1011, 1012, 1013, 1014, 1015, 1016, 1019]
7 [700, 730, 731, 732, 733, 735, 740, 744, 752, 754, 755, 756, 757, 759, 760]
8 [262, 296, 304, 308, 337, 397, 401, 443, 445, 450, 466, 480, 513, 533, 534]
9 [130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 145]
10 [31, 44, 70, 83, 86, 92, 100, 102, 305, 309, 315, 320, 326, 327, 328]
11 [240, 241, 243, 244, 245, 248, 250, 254, 255, 256, 258, 260, 275, 279, 295]
12 [535, 542, 571, 573, 574, 575, 576, 578, 581, 582, 583, 584, 585, 586, 588]
13 [485, 520, 523, 526, 527, 529, 530, 531, 532, 536, 537, 538, 539, 540, 541]


In [ ]:
IS_OUT = []
for i in range(1, 1096):
    IS_OUT.append(True)

trainX = []
trainY = []

for cls, vals in data.items():
  for val in vals:
    trainX.append(cls_vecs[val-1])
    trainY.append(cls)
    IS_OUT[val-1] = False

## SVM Linear

In [ ]:
tokens = bert_tokenizer.tokenize( text_input[0] )
indices, segments = bert_tokenizer.encode( text_input[0] )
print(len(tokens))
print(indices)
print(segments)
print(tokens)

379
[101, 1996, 2317, 2160, 2003, 2036, 4363, 1037, 2485, 3422, 2006, 8936, 1010, 2073, 4559, 2749, 2024, 2055, 2000, 3357, 2039, 1996, 3778, 2006, 2343, 22889, 16429, 13390, 2078, 26038, 17726, 1012, 2021, 2097, 2009, 2147, 1029, 6788, 1005, 1055, 3958, 19382, 2850, 2003, 1999, 10291, 3892, 1012, 7238, 2006, 1996, 6574, 1997, 1037, 2236, 4894, 1012, 2023, 2048, 1011, 3178, 2346, 23467, 2003, 2074, 1037, 5510, 1997, 2054, 2097, 2272, 4826, 1010, 2758, 1996, 4559, 1010, 2043, 1037, 9053, 2147, 2644, 13704, 2003, 2000, 4088, 1012, 1996, 3800, 1010, 2000, 2486, 2041, 1996, 2158, 2027, 2360, 10312, 1996, 4883, 2602, 1010, 22889, 16429, 13390, 2078, 26038, 17726, 1012, 1996, 2111, 2123, 1005, 1056, 5138, 2000, 2022, 6778, 1998, 2000, 2022, 13446, 1997, 2028, 2711, 1010, 26038, 17726, 1012, 2051, 2003, 2551, 2114, 2032, 2085, 1012, 2021, 2097, 1996, 3778, 2147, 1029, 2176, 2086, 3283, 1010, 5606, 1997, 5190, 1997, 16757, 9847, 2114, 26038, 17726, 4214, 2005, 1037, 2236, 4894, 2004, 2092, 101

### Split then Validate

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.svm import SVC

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(trainX, trainY, test_size=0.1, random_state=46)

In [ ]:
svmlin_model = SVC(kernel='linear', C=1)
svmlin_model.fit(X_train, y_train)

predicted_results = []
predicted_results.extend(svmlin_model.predict(X_test))
print(predicted_results)

[4, 3, 1, 6, 2, 5, 13, 8, 7, 8, 12, 12, 1, 4, 2, 10, 4, 1, 7, 9]


In [ ]:
print(metrics.confusion_matrix(y_test, predicted_results))

[[3 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 1 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]]


- error rate

In [ ]:
mat = metrics.confusion_matrix(y_test, predicted_results)
dim = len( mat )
err = 0
for i in range(dim):
  for j in range(dim):
    if i <= j: continue
    if mat[i][j] > 0:
      err += mat[i][j]

err / len(X_test), err

(0.1, 2)

### Whole Model

In [ ]:
svmlin_model = SVC(kernel='linear', C=1)
svmlin_model.fit(trainX, trainY)

SVC(C=1, kernel='linear')

In [ ]:
outX = []
out_indices = []

for i in range(1, 1096):
  if IS_OUT[i-1]:
    outX.append( cls_vecs[i-1] )
    out_indices.append(i)

outX = np.array(outX)

In [ ]:
outX.shape

(900, 768)

In [ ]:
out_predicted_results = []
out_predicted_results.extend(svmlin_model.predict(outX))

In [ ]:
Counter(out_predicted_results)

Counter({1: 47,
         2: 109,
         3: 34,
         4: 58,
         5: 64,
         6: 53,
         7: 46,
         8: 43,
         9: 239,
         10: 37,
         11: 55,
         12: 49,
         13: 66})

In [ ]:
import csv

In [ ]:
with open('SVM.csv', 'w', newline='') as f:
    # create the csv writer
    writer = csv.writer(f)
    writer.writerow(['Id', 'Value'])
    for x, y in zip(out_indices, out_predicted_results):
        writer.writerow([x, int(y)])

## What about dimension reduction then SVM?

### PCA Reduction

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=128)

In [ ]:
cls_vecs = np.array( [x[0] for x in embeddings] )
cls_vecs_reduce = pca.fit_transform(cls_vecs)

In [ ]:
cls_vecs_reduce.shape

(1095, 128)

In [ ]:
IS_OUT = []
for i in range(1, 1096):
    IS_OUT.append(True)

trainX_reduce = []
trainY_reduce = []

for cls, vals in data.items():
  for val in vals:
    trainX_reduce.append( cls_vecs_reduce[val-1] )
    trainY_reduce.append( cls )
    IS_OUT[val-1] = False

trainX_reduce = np.array(trainX_reduce)
trainY_reduce = np.array(trainY_reduce)
# ===

outX_reduce = []
out_indices = []

for i in range(1, 1096):
  if IS_OUT[i-1]:
    outX_reduce.append( cls_vecs_reduce[i-1] )
    out_indices.append(i)

outX_reduce = np.array(outX_reduce)

In [ ]:
trainX_reduce.shape, outX_reduce.shape

((195, 128), (900, 128))

In [ ]:
svmlin_red_model = SVC(kernel='linear', C=1.02)
svmlin_red_model.fit( trainX_reduce, trainY )

SVC(C=1.02, kernel='linear')

In [ ]:
out_predicted_red_results = []
out_predicted_red_results.extend(svmlin_red_model.predict( outX_reduce ) )

In [ ]:
import csv

with open('SVM_red.csv', 'w', newline='') as f:
    # create the csv writer
    writer = csv.writer(f)
    writer.writerow(['Id', 'Value'])
    for x, y in zip(out_indices, out_predicted_red_results):
        writer.writerow([x, int(y)])

## Download Result


In [ ]:
from google.colab import files
files.download('SVM.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
from google.colab import files
files.download('SVM_red.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>